Feat/studentGroupService todos
PSE-Timetable/uftos pull request #127
Opened 2024-07-08 16:23 UTC by jdiester

2024-07-12 21:28 UTC, danieldietzler requested changes

2024-07-12 21:28 UTC, danieldietzler commented on server/src/main/java/de/uftos/services/StudentGroupService.java
> +        .build();
I really like how brief we can write this now thanks to @SuperMarcomen! :)

2024-07-12 21:28 UTC, danieldietzler commented on server/src/test/java/de/uftos/e2e/StudentsTest.java
Why did this class get removed?

2024-07-12 21:28 UTC, danieldietzler commented on server/src/test/java/de/uftos/services/StudentGroupServiceTests.java
> +    Server server = new Server(45, "2024");
This should be broken now

2024-07-18 07:11 UTC, SuperMarcomen approved these changes

2024-07-22 20:35 UTC, danieldietzler approved these changes

2024-07-23 09:30 UTC, merged