feat: generate timetables
PSE-Timetable/uftos pull request #136
Opened 2024-07-11 19:45 UTC by danieldietzler

2024-07-15 14:24 UTC, Lama64 approved these changes

2024-07-15 14:24 UTC, Lama64 commented on web/src/routes/timetable/teacher/+page.svelte
> +    // const response: LessonResponseDto = { lessons: [] };
Should be removed.

2024-07-18 06:55 UTC, SuperMarcomen requested changes

2024-07-18 06:55 UTC, SuperMarcomen commented on web/src/routes/timetable/class/+page.svelte
> +    // const response: LessonResponseDto = { lessons: [] };
```suggestion
```

2024-07-18 06:55 UTC, SuperMarcomen commented on web/src/routes/timetable/teacher/+page.svelte
> +    // const response: LessonResponseDto = { lessons: [] };
```suggestion
```

2024-07-22 19:59 UTC, SuperMarcomen approved these changes

2024-07-22 20:05 UTC, merged