Fix: empty resources
PSE-Timetable/uftos pull request #284
Opened 2024-08-10 13:06 UTC by Lama64

2024-08-10 18:59 UTC, danieldietzler approved these changes
I think it makes sense if we provide proper error messages, since as of right now the user doesn't really now why exactly they got a 400 now

2024-08-10 19:00 UTC, danieldietzler requested changes

2024-08-10 19:00 UTC, danieldietzler commented on server/src/main/java/de/uftos/services/StudentService.java
> +    if (student.firstName().isBlank() ||student.lastName().isBlank()) {
Fix those formatting issues!

2024-08-11 12:59 UTC, danieldietzler approved these changes

2024-08-11 13:30 UTC, Lama64 commented
Wait for merge of #264

2024-08-12 12:42 UTC, merged